/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Attachment, Item, Table } from 'airtable-ts';

export interface Table1 extends Item {
  id: string,
  name: string | null, // Original field: "Name"
  notes: string | null, // Original field: "Notes"
  assignee: string | null, // Original field: "Assignee"
  status: string | null, // Original field: "Status"
  attachments: Attachment[], // Original field: "Attachments"
}

export const Table1table: Table<Table1> = {
  name: 'Table 1',
  baseId: 'appmxwVLLFD7VngR7',
  tableId: 'tblun7TPFGj8R3Ldx',
  mappings: {
    name: 'fldCvUPdAq5AiUc6b', // Original field: "Name"
    notes: 'fldjsVmMeDjWhE9A9', // Original field: "Notes"
    assignee: 'fldgQkwQ0NFEEbb2p', // Original field: "Assignee"
    status: 'flddbMEijtrlJzyQh', // Original field: "Status"
    attachments: 'fldJOA2xW8iMrTmwL', // Original field: "Attachments"
  },
  schema: {
    name: 'string | null',
    notes: 'string | null',
    assignee: 'string | null',
    status: 'string | null',
    attachments: 'Attachment[]',
  },
};

export interface YswsProjectSubmission extends Item {
  id: string,
  codeUrl: string | null, // Original field: "Code URL"
  playableUrl: string | null, // Original field: "Playable URL"
  howDidYouHearAboutThis: string | null, // Original field: "How did you hear about this?"
  whatAreWeDoingWell: string | null, // Original field: "What are we doing well?"
  howCanWeImprove: string | null, // Original field: "How can we improve?"
  firstName: string | null, // Original field: "First Name"
  lastName: string | null, // Original field: "Last Name"
  email: string | null, // Original field: "Email"
  screenshot: Attachment[], // Original field: "Screenshot"
  description: string | null, // Original field: "Description"
  githubUsername: string | null, // Original field: "GitHub Username"
  addressLine1: string | null, // Original field: "Address (Line 1)"
  addressLine2: string | null, // Original field: "Address (Line 2)"
  city: string | null, // Original field: "City"
  stateProvince: string | null, // Original field: "State / Province"
  country: string | null, // Original field: "Country"
  zipPostalCode: string | null, // Original field: "ZIP / Postal Code"
  birthday: number | null, // Original field: "Birthday"
  optionalOverrideHoursSpent: number | null, // Original field: "Optional - Override Hours Spent"
  optionalOverrideHoursSpentJustification: string | null, // Original field: "Optional - Override Hours Spent Justification"
  automationUnifiedJustification: string | null, // Original field: "Automation - Unified Justification"
  justificationHackatimeProjectNameSDateRangeS: string | null, // Original field: "Justification - Hackatime Project Name(s) + Date Range(s)"
  justificationSubmitterHackatimeId: string | null, // Original field: "Justification - Submitter Hackatime ID"
  justificationLapseLinksCommaSeparated: string | null, // Original field: "Justification - Lapse Links, comma-separated"
  justificationSpecificTechnicalFeatures: string | null, // Original field: "Justification - Specific Technical Features"
  justificationDeflationJustification: string | null, // Original field: "Justification - Deflation Justification"
  justificationAlternateTrackingMethod: string | null, // Original field: "Justification - Alternate Tracking Method"
  justificationAdditionalJustification: string | null, // Original field: "Justification - Additional Justification"
  optionalOverrideDuplicateJustification: string | null, // Original field: "Optional - Override Duplicate Justification"
  optionalOverrideAgeJustification: string | null, // Original field: "Optional - Override Age Justification"
  automationSubmitToUnifiedYsws: boolean, // Original field: "Automation - Submit to Unified YSWS"
  automationError: string | null, // Original field: "Automation - Error"
  automationFirstSubmittedAt: number | null, // Original field: "Automation - First Submitted At"
  automationLastUpdatedAt: number | null, // Original field: "Automation - Last Updated At"
  automationYswsRecordId: string | null, // Original field: "Automation - YSWS Record ID"
  loopsSpecialSetfullname: string | null, // Original field: "Loops - Special - setFullName"
  loopsBirthday: number | null, // Original field: "Loops - birthday"
  loopsSpecialSetfulladdress: string | null, // Original field: "Loops - Special - setFullAddress"
  automationStatus: string | null, // Original field: "Automation - Status"
}

export const YswsProjectSubmissiontable: Table<YswsProjectSubmission> = {
  name: 'YSWS Project Submission',
  baseId: 'appmxwVLLFD7VngR7',
  tableId: 'tblq3EOiZTRx7usPx',
  mappings: {
    codeUrl: 'fld5GtF85yGgUeyhU', // Original field: "Code URL"
    playableUrl: 'fldLUVXmPYB4fpiwx', // Original field: "Playable URL"
    howDidYouHearAboutThis: 'fldWp8IIcK6bZQd4b', // Original field: "How did you hear about this?"
    whatAreWeDoingWell: 'fldKWFRC759puBkrZ', // Original field: "What are we doing well?"
    howCanWeImprove: 'fldBXvzEAF24Pfc6G', // Original field: "How can we improve?"
    firstName: 'fld8Lc6US4F4votHE', // Original field: "First Name"
    lastName: 'fld824mcZkpMCNwzY', // Original field: "Last Name"
    email: 'fld7NQmhmMlZshf5d', // Original field: "Email"
    screenshot: 'fldo3rwqB6fxc78RD', // Original field: "Screenshot"
    description: 'fldjRKj6ob36IoSZN', // Original field: "Description"
    githubUsername: 'fld6SOV9ys9XL6zq7', // Original field: "GitHub Username"
    addressLine1: 'fldXxJLXVMNKuVNg1', // Original field: "Address (Line 1)"
    addressLine2: 'fld6yUPdwTiX8xRQ6', // Original field: "Address (Line 2)"
    city: 'fldPSVGSw5zDAwyrD', // Original field: "City"
    stateProvince: 'fldBtbiAAiRGwtDZT', // Original field: "State / Province"
    country: 'fldWC5ksMerKOCZ3d', // Original field: "Country"
    zipPostalCode: 'fldmVMyK3UhyYFRtG', // Original field: "ZIP / Postal Code"
    birthday: 'fld2u428ByrFLmuT0', // Original field: "Birthday"
    optionalOverrideHoursSpent: 'fld1GKihMlpaudz0K', // Original field: "Optional - Override Hours Spent"
    optionalOverrideHoursSpentJustification: 'fldK7nP2DrYrMT6L7', // Original field: "Optional - Override Hours Spent Justification"
    automationUnifiedJustification: 'fld7CoW9ExgrSq6BO', // Original field: "Automation - Unified Justification"
    justificationHackatimeProjectNameSDateRangeS: 'fldyCoLoILPE6n311', // Original field: "Justification - Hackatime Project Name(s) + Date Range(s)"
    justificationSubmitterHackatimeId: 'fldIpwvFFrIxMI7UX', // Original field: "Justification - Submitter Hackatime ID"
    justificationLapseLinksCommaSeparated: 'fldjibfDH4C4PaTr4', // Original field: "Justification - Lapse Links, comma-separated"
    justificationSpecificTechnicalFeatures: 'fldnd2dTqu5mHar25', // Original field: "Justification - Specific Technical Features"
    justificationDeflationJustification: 'fldwzSo2cVch5ORg9', // Original field: "Justification - Deflation Justification"
    justificationAlternateTrackingMethod: 'fldNhsCyWAlYHfrlz', // Original field: "Justification - Alternate Tracking Method"
    justificationAdditionalJustification: 'fldzSsCU5lXOIG8Mt', // Original field: "Justification - Additional Justification"
    optionalOverrideDuplicateJustification: 'fld2VqenfHmpwgUEp', // Original field: "Optional - Override Duplicate Justification"
    optionalOverrideAgeJustification: 'fldFEYH0erZmOZIO2', // Original field: "Optional - Override Age Justification"
    automationSubmitToUnifiedYsws: 'fldXV0P3uYDbVVsBA', // Original field: "Automation - Submit to Unified YSWS"
    automationError: 'fldhjmzkZwyW31hiE', // Original field: "Automation - Error"
    automationFirstSubmittedAt: 'fldhhQuLIExNIsqSr', // Original field: "Automation - First Submitted At"
    automationLastUpdatedAt: 'fldkWFmGBvEYTDPnX', // Original field: "Automation - Last Updated At"
    automationYswsRecordId: 'fldtQWf5vvDObjx3j', // Original field: "Automation - YSWS Record ID"
    loopsSpecialSetfullname: 'fldrFLFVR9U6VQvFO', // Original field: "Loops - Special - setFullName"
    loopsBirthday: 'fldZOiiEXROdrPKvJ', // Original field: "Loops - birthday"
    loopsSpecialSetfulladdress: 'fld3gE3PQAwtmUeb7', // Original field: "Loops - Special - setFullAddress"
    automationStatus: 'fldc8R6ZpjWP8HfsX', // Original field: "Automation - Status"
  },
  schema: {
    codeUrl: 'string | null',
    playableUrl: 'string | null',
    howDidYouHearAboutThis: 'string | null',
    whatAreWeDoingWell: 'string | null',
    howCanWeImprove: 'string | null',
    firstName: 'string | null',
    lastName: 'string | null',
    email: 'string | null',
    screenshot: 'Attachment[]',
    description: 'string | null',
    githubUsername: 'string | null',
    addressLine1: 'string | null',
    addressLine2: 'string | null',
    city: 'string | null',
    stateProvince: 'string | null',
    country: 'string | null',
    zipPostalCode: 'string | null',
    birthday: 'number | null',
    optionalOverrideHoursSpent: 'number | null',
    optionalOverrideHoursSpentJustification: 'string | null',
    automationUnifiedJustification: 'string | null',
    justificationHackatimeProjectNameSDateRangeS: 'string | null',
    justificationSubmitterHackatimeId: 'string | null',
    justificationLapseLinksCommaSeparated: 'string | null',
    justificationSpecificTechnicalFeatures: 'string | null',
    justificationDeflationJustification: 'string | null',
    justificationAlternateTrackingMethod: 'string | null',
    justificationAdditionalJustification: 'string | null',
    optionalOverrideDuplicateJustification: 'string | null',
    optionalOverrideAgeJustification: 'string | null',
    automationSubmitToUnifiedYsws: 'boolean',
    automationError: 'string | null',
    automationFirstSubmittedAt: 'number | null',
    automationLastUpdatedAt: 'number | null',
    automationYswsRecordId: 'string | null',
    loopsSpecialSetfullname: 'string | null',
    loopsBirthday: 'number | null',
    loopsSpecialSetfulladdress: 'string | null',
    automationStatus: 'string | null',
  },
};

export interface YswsConfig extends Item {
  id: string,
  key: string | null, // Original field: "Key"
  value: string | null, // Original field: "Value"
}

export const YswsConfigtable: Table<YswsConfig> = {
  name: 'YSWS Config',
  baseId: 'appmxwVLLFD7VngR7',
  tableId: 'tblCCPaCvldOGj71B',
  mappings: {
    key: 'fldsh3FxWkzYilJlc', // Original field: "Key"
    value: 'fldUOjLoFFuE0rbv2', // Original field: "Value"
  },
  schema: {
    key: 'string | null',
    value: 'string | null',
  },
};